# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1OgYHy-GodlACzqT28RydNjkxHfiJyu_q
"""

import pandas as pd

# Load the dataset
url = "https://archive.ics.uci.edu/ml/machine-learning-databases/heart-disease/processed.cleveland.data"
column_names = ["age", "sex", "cp", "trestbps", "chol", "fbs", "restecg", "thalach", "exang", "oldpeak", "slope", "ca", "thal", "target"]
heart_data = pd.read_csv(url, header=None, names=column_names, na_values="?")

# Display first few rows
print(heart_data.head())

# Describe the dataset
print(heart_data.describe())

import plotly.graph_objects as go
fig = go.Figure()

# Adding traces
fig.add_trace(go.Scatter(x=heart_data['age'], y=heart_data['chol'], mode='markers', name='Cholesterol'))

# Updating layout
fig.update_layout(title='Cholesterol Levels by Age',
                  xaxis_title='Age',
                  yaxis_title='Cholesterol',
                  template='plotly_dark')

fig.show()

# Updating traces
fig.update_traces(marker=dict(size=10, color='rgba(152, 0, 0, .8)', line=dict(width=2, color='DarkSlateGrey')))

# Updating axes
fig.update_xaxes(title_font=dict(size=18, family='Courier', color='crimson'),
                 tickfont=dict(size=14, family='Arial', color='crimson'))
fig.update_yaxes(title_font=dict(size=18, family='Courier', color='crimson'),
                 tickfont=dict(size=14, family='Arial', color='crimson'))

fig.show()